<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="3" ignored="0" total="6" passed="0">
  <reporter-output>
    <line>
      <![CDATA[方法<TestngDemo>执行失败，重试第1次]]>
    </line>
    <line>
      <![CDATA[方法<TestngDemo>执行失败，重试第2次]]>
    </line>
    <line>
      <![CDATA[方法<TestngDemo>执行失败，重试第3次]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="13827" started-at="2018-01-24T11:54:52Z" finished-at="2018-01-24T11:55:06Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="13827" started-at="2018-01-24T11:54:52Z" finished-at="2018-01-24T11:55:06Z">
      <class name="demo20180107.TestngExe">
        <test-method status="SKIP" signature="TestngDemo(demo20180107.ExcelElement)[pri:0, instance:demo20180107.TestngExe@1060b431]" name="TestngDemo" duration-ms="6612" started-at="2018-01-24T19:54:57Z" data-provider="ExcelData" finished-at="2018-01-24T19:55:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ExcelElement [type=get, url=http://59.110.139.20:8080/goods/UserServlet?method=loginMobile&loginname=test1&loginpass=test1, params=null, header=null, run=是, check=$.code=1, correction=id=$.uid;test2=$.code, result=null, getResult()=null, getCheck()=$.code=1, getCorrection()=id=$.uid;test2=$.code, getRun()=是, getType()=get, getUrl()=http://59.110.139.20:8080/goods/UserServlet?method=loginMobile&loginname=test1&loginpass=test1, getParams()=null, getHeader()=null, getClass()=class demo20180107.ExcelElement, hashCode()=1029472813, toString()=demo20180107.ExcelElement@3d5c822d]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at demo20180107.TestngExe.TestngDemo(TestngExe.java:60)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[方法<TestngDemo>执行失败，重试第1次]]>
            </line>
          </reporter-output>
        </test-method> <!-- TestngDemo -->
        <test-method status="SKIP" signature="TestngDemo(demo20180107.ExcelElement)[pri:0, instance:demo20180107.TestngExe@1060b431]" name="TestngDemo" duration-ms="99" started-at="2018-01-24T19:55:04Z" data-provider="ExcelData" finished-at="2018-01-24T19:55:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ExcelElement [type=get, url=http://59.110.139.20:8080/goods/UserServlet?method=loginMobile&loginname=test1&loginpass=test1, params=null, header=null, run=是, check=$.code=1, correction=id=$.uid;test2=$.code, result=null, getResult()=null, getCheck()=$.code=1, getCorrection()=id=$.uid;test2=$.code, getRun()=是, getType()=get, getUrl()=http://59.110.139.20:8080/goods/UserServlet?method=loginMobile&loginname=test1&loginpass=test1, getParams()=null, getHeader()=null, getClass()=class demo20180107.ExcelElement, hashCode()=888287133, toString()=demo20180107.ExcelElement@34f22f9d]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at demo20180107.TestngExe.TestngDemo(TestngExe.java:60)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[方法<TestngDemo>执行失败，重试第2次]]>
            </line>
          </reporter-output>
        </test-method> <!-- TestngDemo -->
        <test-method status="SKIP" signature="TestngDemo(demo20180107.ExcelElement)[pri:0, instance:demo20180107.TestngExe@1060b431]" name="TestngDemo" duration-ms="78" started-at="2018-01-24T19:55:04Z" data-provider="ExcelData" finished-at="2018-01-24T19:55:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ExcelElement [type=get, url=http://59.110.139.20:8080/goods/UserServlet?method=loginMobile&loginname=test1&loginpass=test1, params=null, header=null, run=是, check=$.code=1, correction=id=$.uid;test2=$.code, result=null, getResult()=null, getCheck()=$.code=1, getCorrection()=id=$.uid;test2=$.code, getRun()=是, getType()=get, getUrl()=http://59.110.139.20:8080/goods/UserServlet?method=loginMobile&loginname=test1&loginpass=test1, getParams()=null, getHeader()=null, getClass()=class demo20180107.ExcelElement, hashCode()=1076071888, toString()=demo20180107.ExcelElement@40238dd0]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at demo20180107.TestngExe.TestngDemo(TestngExe.java:60)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[方法<TestngDemo>执行失败，重试第3次]]>
            </line>
          </reporter-output>
        </test-method> <!-- TestngDemo -->
        <test-method status="FAIL" signature="TestngDemo(demo20180107.ExcelElement)[pri:0, instance:demo20180107.TestngExe@1060b431]" name="TestngDemo" duration-ms="37" started-at="2018-01-24T19:55:05Z" data-provider="ExcelData" finished-at="2018-01-24T19:55:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ExcelElement [type=get, url=http://59.110.139.20:8080/goods/UserServlet?method=loginMobile&loginname=test1&loginpass=test1, params=null, header=null, run=是, check=$.code=1, correction=id=$.uid;test2=$.code, result=null, getResult()=null, getCheck()=$.code=1, getCorrection()=id=$.uid;test2=$.code, getRun()=是, getType()=get, getUrl()=http://59.110.139.20:8080/goods/UserServlet?method=loginMobile&loginname=test1&loginpass=test1, getParams()=null, getHeader()=null, getClass()=class demo20180107.ExcelElement, hashCode()=229995302, toString()=demo20180107.ExcelElement@db57326]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at demo20180107.TestngExe.TestngDemo(TestngExe.java:60)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestngDemo -->
        <test-method status="FAIL" signature="TestngDemo(demo20180107.ExcelElement)[pri:0, instance:demo20180107.TestngExe@1060b431]" name="TestngDemo" duration-ms="458" started-at="2018-01-24T19:55:05Z" data-provider="ExcelData" finished-at="2018-01-24T19:55:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ExcelElement [type=get, url=http://www.baidu.com?pid=E2BBEDC09FAA4406B8D85C96DF6281CF&test2=1, params=null, header=null, run=是, check=null, correction=null, result=null, getResult()=null, getCheck()=null, getCorrection()=null, getRun()=是, getType()=get, getUrl()=http://www.baidu.com?pid=E2BBEDC09FAA4406B8D85C96DF6281CF&test2=1, getParams()=null, getHeader()=null, getClass()=class demo20180107.ExcelElement, hashCode()=1830745997, toString()=demo20180107.ExcelElement@6d1ef78d]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at demo20180107.TestngExe.TestngDemo(TestngExe.java:60)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestngDemo -->
        <test-method status="FAIL" signature="TestngDemo(demo20180107.ExcelElement)[pri:0, instance:demo20180107.TestngExe@1060b431]" name="TestngDemo" duration-ms="66" started-at="2018-01-24T19:55:05Z" data-provider="ExcelData" finished-at="2018-01-24T19:55:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ExcelElement [type=get, url=http://www.baidu.com?pid=E2BBEDC09FAA4406B8D85C96DF6281CF&test2=1, params=null, header=null, run=是, check=null, correction=null, result=null, getResult()=null, getCheck()=null, getCorrection()=null, getRun()=是, getType()=get, getUrl()=http://www.baidu.com?pid=E2BBEDC09FAA4406B8D85C96DF6281CF&test2=1, getParams()=null, getHeader()=null, getClass()=class demo20180107.ExcelElement, hashCode()=1574029810, toString()=demo20180107.ExcelElement@5dd1c9f2]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at demo20180107.TestngExe.TestngDemo(TestngExe.java:60)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestngDemo -->
      </class> <!-- demo20180107.TestngExe -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
